name: SentinelPay CI

on:
  push:
    branches:
      - cicd-pipeline

  pull_request:
    branches:
      - main

jobs:
  test-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Confirm workflow is running
        run: echo "SentinelPay GitHub Actions pipeline is working"

  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full Git history
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          GITLEAKS_VERSION="8.28.0"
          curl -sSL "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz" \
            -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          sudo mv gitleaks /usr/local/bin/gitleaks
          gitleaks version

      - name: Run SentinelPay Gitleaks scan
        run: |
          gitleaks git . \
            --config .gitleaks.toml \
            --redact \
            --verbose
